# Generated by Django 5.0.3 on 2024-04-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students_name', models.CharField(max_length=50)),
                ('student_subject', models.CharField(max_length=100)),
                ('student_age', models.IntegerField()),
            ],
        ),
    ]
